apiVersion: constraints.gatekeeper.sh/v1beta1
kind: workflowLabel
metadata:
  name: workflow
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["workflow"]

